# Prompt settings - Based off the spaceship prompt
#

# Spaceship defaults, these are currently not pulling correctly from upstream
MY_SPACESHIP_PROMPT_DEFAULT_PREFIX='['
MY_SPACESHIP_PROMPT_DEFAULT_SUFFIX='] '

# Kubernetes
SPACESHIP_KUBECONTEXT_PREFIX="${MY_SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_KUBECONTEXT_SUFFIX="${MY_SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_KUBECONTEXT_SYMBOL='⎈ '

# Go
SPACESHIP_GOLANG_PREFIX="${MY_SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_GOLANG_SUFFIX="${MY_SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_GOLANG_SYMBOL='go '

# AWS
SPACESHIP_AWS_PREFIX="${MY_SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_AWS_SUFFIX="${MY_SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_AWS_SYMBOL="☁️  "

# PYENV
SPACESHIP_PYENV_PREFIX="${MY_SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_PYENV_SUFFIX="${MY_SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
