# Prompt settings - Based off the spaceship prompt
#

# Spaceship defaults, these are currently not pulling correctly from upstream
SPACESHIP_PROMPT_DEFAULT_PREFIX='['
SPACESHIP_PROMPT_DEFAULT_SUFFIX='] '

# Kubernetes
SPACESHIP_KUBECONTEXT_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_KUBECONTEXT_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_KUBECONTEXT_SYMBOL='⎈ '

# Go
SPACESHIP_GOLANG_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_GOLANG_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_GOLANG_SYMBOL='go '

# AWS
SPACESHIP_AWS_PREFIX="${SPACESHIP_PROMPT_DEFAULT_PREFIX}"
SPACESHIP_AWS_SUFFIX="${SPACESHIP_PROMPT_DEFAULT_SUFFIX}"
SPACESHIP_AWS_SYMBOL="☁️  "
